#!/bin/bash

if [ -z "$1" ]
then
    echo "Do nothing ..."
else
    adb shell input tap 800 800
    if [ "$1" = "zone" ]
    then
        adb shell input text "440020372@ntunhs.edu.tw"
        adb shell input keyevent KEYCODE_TAB
        adb shell input text "gggggggg"
    elif [ "$1" = "david"  ]
    then
        adb shell input text "david77115@gmail.com"
        adb shell input keyevent KEYCODE_TAB
        adb shell input text "batu05dcard"
    elif [ "$1" = "aangle" ]
    then
        adb shell input text "dcardandroid@dcard.tw"
        adb shell input keyevent KEYCODE_TAB
	adb shell input text "95URRLpdtRhbMbh"
    elif [[ "$1" == *badu* ]]
    then
        adb shell input text "$1@dcard.cc"
        adb shell input keyevent KEYCODE_TAB
        adb shell input keyevent KEYCODE_TAB
        adb shell input keyevent KEYCODE_TAB
        adb shell input text "badubadu"
    fi
    adb shell input keyevent KEYCODE_TAB
    adb shell input keyevent KEYCODE_ENTER
fi
