#!/bin/bash

if [ -z "$1" ]
then
    echo "Do nothing ..."
else
    adb shell input tap 800 800
    if [ "$1" = "zone" ]
    then
        adb shell input text "440020372@ntunhs.edu.tw"
        adb shell input tap 990 510
        adb shell input tap 990 510
        adb shell input text "gggggggg"
    elif [ "$1" = "fantacy" ]
    then
        adb shell input text "fantasy@dcard.cc"
        adb shell input tap 990 510
        adb shell input tap 990 510
        adb shell input text "pkjay123"
    elif [ "$1" = "dai" ]
    then 
        adb shell input text "daidoujichen@gmail.com"
	adb shell input tap 990 510
	adb shell input tap 990 510
	adb shell input text "caroltest"
    elif [ "$1" = "david"  ]
    then
        adb shell input text "david77115@gmail.com"
        adb shell input tap 990 510
        adb shell input tap 990 510
        adb shell input text "batu05dcard"
    elif [ "$1" = "aangle" ]
    then
        adb shell input text "dcardandroid@dcard.tw"
        adb shell input tap 990 510
        adb shell input tap 990 510
	adb shell input text "95URRLpdtRhbMbh"
    elif [[ "$1" == *badu* ]]
    then
        adb shell input text "$1@dcard.cc"
        adb shell input tap 990 510
        adb shell input tap 990 510
        adb shell input text "badubadu"
    else
        accountName=$1
        regex='(.*)\+([0-9]+)$'
        if [[ $accountName =~ $regex ]]
        then
            user=${BASH_REMATCH[1]}
            if [[ $user = "giny" ]] || [[ $user = "benben" ]]
            then
                pw=${BASH_REMATCH[2]}
                size=${#pw} 
                if [[ $size -eq 3 ]]
                then
                    adb shell input text "$accountName@dcard.cc"
                    adb shell input tap 990 510
                    adb shell input tap 990 510
                    adb shell input text "$pw$pw"                
                elif [[ $size -eq 2 ]]
                then
                    adb shell input text "$accountName@dcard.cc"
                    adb shell input tap 990 510
                    adb shell input tap 990 510
                    adb shell input text "$pw$pw$pw"
                elif [[ $size -eq 1 ]]
                then
                adb shell input text "$accountName@dcard.cc"
                    adb shell input tap 990 510
                    adb shell input tap 990 510
                    adb shell input text "$pw$pw$pw$pw$pw$pw"            
                else
                    echo "Can not organize the number: '$pw'"
                    exit 0
                fi    
            else
                echo "Can not fetch the number from '$accountName'"
                exit 0
            fi
            
        else
            echo "Can not fetch the number from '$accountName'"
            exit 0
        fi
    fi
    adb shell input keyevent KEYCODE_TAB
    adb shell input keyevent KEYCODE_ENTER
fi
